name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Checkout github-actions
        uses: actions/checkout@v6
        with:
          repository: kubecost/github-actions
          token: ${{ secrets.ACTION_PAT }}
          path: .github-actions
          sparse-checkout: lychee-action

      - name: Link Checker
        id: lychee
        uses: ./.github-actions/lychee-action
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail: true
          debug: false
          args: --verbose --no-progress --exclude-path '.github-actions' --base . -E './**/*.md' './**/*.html'

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
